# Generated by Django 4.1.3 on 2022-12-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desires_model",
            name="d1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d1t1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d1t2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d1t3",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d2t1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d2t2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d2t3",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d3",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d3t1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d3t2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d3t3",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d4",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d4t1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d4t2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d4t3",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d5",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d5t1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d5t2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="desires_model",
            name="d5t3",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
