# Generated by Django 4.1.3 on 2022-12-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_courses_model_credit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Days_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="desires_model",
            name="day1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="desires_model",
            name="day2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="desires_model",
            name="day3",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="desires_model",
            name="day4",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="desires_model",
            name="day5",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
