# Generated by Django 4.1.3 on 2022-12-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_days_model_desires_model_day1_desires_model_day2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="days_model",
            name="title",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="dt_model",
            name="time_value",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
