# Generated by Django 4.1.3 on 2022-12-12 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_courses_model_number_alter_courses_model_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="desires_model",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
