# Generated by Django 4.0.2 on 2022-12-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_dt_model_group_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
